[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
      let cmd = 'tools\\update-dll-mingw'
    elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
      let cmd = 'gmake'
    else
    let cmd = 'make'
 endif
   let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'mhinz/vim-startify'

[[plugins]]
repo = 'Lokaltog/vim-easymotion'

[[plugins]]
repo = 'Raimondi/delimitMate'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'jpo/vim-railscasts-theme'
hook_add = '''
  set background=dark
  au MyAutoCmd VimEnter * nested colorscheme railscasts
'''

[[plugins]]
repo = 'osyo-manga/vim-anzu'
