[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'mhinz/vim-startify'

[[plugins]]
repo = 'Lokaltog/vim-easymotion'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'SirVer/ultisnips'

[[plugins]]
repo = 'fatih/molokai'
hook_add = '''
  set background=dark
  au MyAutoCmd VimEnter * nested colorscheme molokai
'''

[[plugins]]
repo = 'ConradIrwin/vim-bracketed-paste'

[[plugins]]
repo = 'junegunn/vim-easy-align'

[[plugins]]
repo = 'tobyS/vmustache'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = "tpope/vim-fugitive"

[[plugins]]
repo = 'tpope/vim-abolish'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
