[[plugins]]
repo = 'Shougo/dein.vim'

# syntax
[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = 'context_filetype.vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'call hooks#lightline#init()'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
	highlight clear SignColumn
'''

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = 'call hooks#theme#init()'

[[plugins]]
repo = 'ConradIrwin/vim-bracketed-paste'

# cvs
[[plugins]]
repo = "tpope/vim-fugitive"

# edit
[[plugins]]
repo = 'editorconfig/editorconfig-vim'

# LSP
[[plugins]]
repo = 'neoclide/coc.nvim'
build = './install.sh'
hook_add = 'call hooks#coc#init()'
merged = '0'
rev = 'release'

# icons
[[plugins]]
repo = 'ryanoasis/vim-devicons'

# motions
[[plugins]]
repo = 'rhysd/clever-f.vim'

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = 'call hooks#easymotion#init()'
depends = 'incsearch-easymotion.vim'

[[plugins]]
repo = 'machakann/vim-sandwich'

[[plugins]]
repo = 'haya14busa/incsearch.vim'

[[plugins]]
repo = 'haya14busa/incsearch-fuzzy.vim'
depends = 'incsearch.vim'

[[plugins]]
repo = 'haya14busa/incsearch-easymotion.vim'
depends = 'incsearch-fuzzy.vim'

# filer
[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = 'call hooks#defx#init()'

[[plugins]]
repo = 'kristijanhusak/defx-git'
depends = 'defx.nvim'

[[plugins]]
repo = 'kristijanhusak/defx-icons'
depends = 'defx.nvim'

# animate
[[plugins]]
repo = 'camspiers/animate.vim'
hook_add = 'call hooks#animate#init()'

# misc
[[plugins]]
repo = 'wakatime/vim-wakatime'

[[plugins]]
repo = 'mjhd-devlion/coc-denite'
rev = 'feat/support-code-action'
