[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'terryma/vim-multiple-cursors'
on_i = 1

[[plugins]]
repo = 'Raimondi/delimitMate'
on_i = 1

# TS/JS
[[plugins]]
repo = 'fleischie/vim-styled-components'
on_ft = ['javascript', 'javascript.jsx', 'typescript', 'typescript.tsx']

# Dart
[[plugins]]
repo = 'dart-lang/dart-vim-plugin'
on_ft = ['dart']

[[plugins]]
repo = 'thosakwe/vim-flutter'
on_ft = ['dart']
hook_add = 'call hooks#flutter#init()'

# Fuzzy Search
[[plugins]]
repo = 'Shougo/denite.nvim'
depends = 'vim-devicons'
on_cmd = 'Denite'
hook_add = 'call hooks#denite#keymaps()'
hook_post_source = 'call hooks#denite#init()'
