[[plugins]]
repo = 'Shougo/dein.vim'

# カーソルの位置でシンタックス切り替え
[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = 'context_filetype.vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'call hooks#lightline#init()'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
	highlight clear SignColumn
'''

[[plugins]]
repo = 'hzchirs/vim-material'
hook_add = 'call hooks#theme#init()'

[[plugins]]
repo = 'ConradIrwin/vim-bracketed-paste'


[[plugins]]
repo = "tpope/vim-fugitive"

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

# LSP
[[plugins]]
repo = 'neoclide/coc.nvim'
build = './install.sh'
hook_add = 'call hooks#coc#init()'
merged = '0'
rev = 'release'

# icons
[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'rhysd/clever-f.vim'

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = 'call hooks#easymotion#init()'
depends = 'incsearch-easymotion.vim'

[[plugins]]
repo = 'haya14busa/incsearch.vim'

[[plugins]]
repo = 'haya14busa/incsearch-fuzzy.vim'
depends = 'incsearch.vim'

[[plugins]]
repo = 'haya14busa/incsearch-easymotion.vim'
depends = 'incsearch-fuzzy.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = 'call hooks#defx#init()'

[[plugins]]
repo = 'kristijanhusak/defx-icons'
