[[plugins]]
repo = 'Shougo/dein.vim'

# カーソルの位置でシンタックス切り替え
[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = 'context_filetype.vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'call hooks#lightline#init()'

[[plugins]]
repo = 'mhinz/vim-startify'
hook_add = 'call hooks#startify#init()'

[[plugins]]
repo = 'Lokaltog/vim-easymotion'
hook_add = 'call hooks#easymotion#init()'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
	highlight clear SignColumn
'''

[[plugins]]
repo = 'fatih/molokai'
hook_add = 'call hooks#molokai#init()'

[[plugins]]
repo = 'ConradIrwin/vim-bracketed-paste'

[[plugins]]
repo = 'junegunn/vim-easy-align'
hook_add = '''
	vnoremap <silent> <Enter> :EasyAlign<cr>
'''

[[plugins]]
repo = "tpope/vim-fugitive"

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

# Completion
[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = 'call hooks#deoplete#init()'

[[plugins]]
repo = 'lighttiger2505/deoplete-vim-lsp'
depends = ['deoplete.nvim', 'vim-lsp']

# LSP
[[plugins]]
repo = 'prabirshrestha/vim-lsp'
depends = 'async.vim'
hook_add = 'call hooks#vimlsp#init()'

[[plugins]]
repo = 'prabirshrestha/async.vim'

# Side Panel
[[plugins]]
repo = 'liuchengxu/vista.vim'
depends = 'vim-lsp'
hook_add = 'call hooks#vista#init()'

# icons
[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'rhysd/clever-f.vim'
