[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'terryma/vim-multiple-cursors'
on_i = 1

[[plugins]]
repo = 'Raimondi/delimitMate'
on_i = 1

[[plugins]]
repo = 'ianks/vim-tsx'
on_ft = ['tsx', 'ts', 'typescript']

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['tsx', 'ts', 'typescript']

[[plugins]]
repo = 'prettier/vim-prettier'
on_ft = ['js', 'jsx']

[[plugins]]
repo = 'fleischie/vim-styled-components'
on_ft = ['js', 'jsx', 'typescript']

[[plugins]]
repo = 'peitalin/vim-jsx-typescript'
on_ft = ['js', 'jsx', 'typescript']
